Repository numbersprotocol/capture-lite, pull requests merged in 2020-11, with the labels that each got.

#166 Rebuild Proof Details Page with Angular-Material Library
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/pages/login/login.page.scss
  src/app/pages/profile/profile.page.scss
  src/app/pages/profile/profile.page.ts
  src/app/pages/proof/proof.page.html
  src/app/pages/proof/proof.page.scss
  src/app/pages/signup/signup.page.scss
  src/app/pages/storage/proof/information/information-routing.module.ts
  src/app/pages/storage/proof/information/information.module.ts
  src/app/pages/storage/proof/information/information.page.html
  src/app/pages/storage/proof/information/information.page.scss
  src/app/pages/storage/proof/information/information.page.spec.ts
  src/app/pages/storage/proof/information/information.page.ts
  src/app/pages/storage/proof/proof-routing.module.ts
  src/app/pages/storage/proof/proof.module.ts
  src/app/pages/storage/proof/proof.page.html
  src/app/pages/storage/proof/proof.page.scss
  src/app/pages/storage/proof/proof.page.spec.ts
  src/app/pages/storage/proof/proof.page.ts
  src/app/pages/storage/storage-routing.module.ts
  src/app/pages/storage/storage.page.html
  src/app/pages/storage/storage.page.scss
  src/app/services/blocking-action/blocking-action.service.ts
  src/app/services/collector/information/capacitor-provider/capacitor-provider.ts
  src/app/services/collector/information/information-provider.ts
  src/app/services/collector/signature/signature-provider.ts
  src/app/services/collector/signature/web-crypto-api-provider/web-crypto-api-provider.spec.ts
  src/app/services/collector/signature/web-crypto-api-provider/web-crypto-api-provider.ts
  src/app/services/confirm-alert/confirm-alert.service.ts
  src/app/services/publisher/publishers-alert/publishers-alert.service.ts
  src/app/utils/preferences/preference-manager.ts
  src/assets/i18n/en-us.json
  src/assets/i18n/zh-tw.json
  src/global.scss
  src/theme/variables.scss
Labels: enhancement, uiux

#179 fix ios iphoneX header Occlude
  src/global.scss
Labels: uiux

#171 Activity (History) Page
  src/app/pages/storage/activity/activity-routing.module.ts
  src/app/pages/storage/activity/activity.module.ts
  src/app/pages/storage/activity/activity.page.html
  src/app/pages/storage/activity/activity.page.scss
  src/app/pages/storage/activity/activity.page.spec.ts
  src/app/pages/storage/activity/activity.page.ts
  src/app/pages/storage/storage-routing.module.ts
  src/app/pages/storage/storage.page.html
  src/assets/i18n/en-us.json
  src/assets/i18n/zh-tw.json
  src/global.scss
Labels: uiux

#170 Inbox Page
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/pages/storage/inbox/inbox-routing.module.ts
  src/app/pages/storage/inbox/inbox.module.ts
  src/app/pages/storage/inbox/inbox.page.html
  src/app/pages/storage/inbox/inbox.page.scss
  src/app/pages/storage/inbox/inbox.page.spec.ts
  src/app/pages/storage/inbox/inbox.page.ts
  src/app/pages/storage/storage-routing.module.ts
  src/app/pages/storage/storage.page.html
  src/app/pages/storage/storage.page.scss
  src/assets/i18n/en-us.json
  src/assets/i18n/zh-tw.json
Labels: uiux

#178 Comply UI design
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/pages/about/about.page.scss
  src/app/pages/privacy/privacy.page.scss
  src/app/pages/profile/profile.page.scss
  src/app/pages/settings/settings.page.scss
  src/app/pages/storage/proof/information/information.page.html
  src/app/pages/storage/proof/information/information.page.scss
  src/app/pages/storage/proof/information/information.page.ts
  src/app/pages/storage/proof/options-menu/options-menu.component.html
  src/app/pages/storage/proof/options-menu/options-menu.component.scss
  src/app/pages/storage/proof/options-menu/options-menu.component.spec.ts
  src/app/pages/storage/proof/options-menu/options-menu.component.ts
  src/app/pages/storage/proof/proof.module.ts
  src/app/pages/storage/proof/proof.page.html
  src/app/pages/storage/proof/proof.page.scss
  src/app/pages/storage/proof/proof.page.spec.ts
  src/app/pages/storage/proof/proof.page.ts
  src/app/pages/storage/proof/sending-post-capture/sending-post-capture.page.scss
  src/app/pages/storage/storage.page.html
  src/app/shared/post-capture-card/post-capture-card.component.spec.ts
  src/app/shared/post-capture-card/post-capture-card.component.ts
  src/assets/i18n/en-us.json
  src/assets/i18n/zh-tw.json
  src/global.scss
  src/theme/variables.scss
Labels: uiux

#193 WORKAROUND: Catch Error from Capacitor.Filesystem.deleteFile on Android or iOS Devices
  src/app/pages/home/inbox/inbox.page.ts
  src/app/utils/storage/storage.ts
Labels: workaround

#204 Fix #202, #201 and #198
  android/app/src/main/assets/capacitor.config.json
  android/app/src/main/res/values/strings.xml
  capacitor.config.json
  src/app/pages/home/asset/asset.page.html
  src/app/pages/home/asset/sending-post-capture/sending-post-capture.page.html
  src/app/pages/home/home.page.html
  src/app/pages/home/home.page.ts
  src/app/pages/home/inbox/inbox.page.ts
  src/app/services/publisher/numbers-storage/numbers-storage-api.service.ts
  src/app/shared/post-capture-card/post-capture-card.component.html
  src/app/shared/post-capture-card/post-capture-card.component.spec.ts
  src/app/shared/post-capture-card/post-capture-card.component.ts
  src/assets/i18n/en-us.json
  src/assets/i18n/zh-tw.json
Labels: uiux, workaround

#222 Show 'Nothing Here' on inbox page when no item to show. #207
  src/app/pages/home/inbox/inbox.page.html
  src/app/pages/home/inbox/inbox.page.scss
  src/app/services/publisher/numbers-storage/numbers-storage-api.service.ts
Labels: uiux

#224 Required User Name on Sign-Up Page
  src/app/pages/home/asset/sending-post-capture/sending-post-capture.page.ts
  src/app/pages/home/home.page.html
  src/app/pages/home/home.page.ts
  src/app/pages/profile/profile.page.html
  src/app/pages/profile/profile.page.ts
  src/app/pages/signup/signup.page.ts
  src/app/services/publisher/numbers-storage/numbers-storage-api.service.ts
  src/assets/i18n/en-us.json
  src/assets/i18n/zh-tw.json
Labels: enhancement

#223 Rename publishing proof to registering asset. #208
  src/app/services/publisher/publisher.ts
  src/assets/i18n/en-us.json
  src/assets/i18n/zh-tw.json
Labels: uiux

#268 Refactor Blocking Action Service
  src/app/services/blocking-action/blocking-action.service.spec.ts
  src/app/services/blocking-action/blocking-action.service.ts
Labels: code

#269 Refactor PreferenceManager and Preferences
  src/app/app.component.ts
  src/app/guards/auth/auth.guard.ts
  src/app/pages/home/activity/activity.page.ts
  src/app/pages/home/home.page.ts
  src/app/pages/privacy/privacy.page.spec.ts
  src/app/pages/privacy/privacy.page.ts
  src/app/pages/profile/profile.page.ts
  src/app/pages/settings/settings.page.spec.ts
  src/app/pages/settings/settings.page.ts
  src/app/services/collector/facts/capacitor-provider/capacitor-facts-provider.service.spec.ts
  src/app/services/collector/facts/capacitor-provider/capacitor-facts-provider.service.ts
  src/app/services/collector/facts/capacitor-provider/capacitor-provider.ts
  src/app/services/collector/signature/web-crypto-api-provider/web-crypto-api-provider.ts
  src/app/services/collector/signature/web-crypto-api-provider/web-crypto-api-signature-provider.service.spec.ts
  src/app/services/collector/signature/web-crypto-api-provider/web-crypto-api-signature-provider.service.ts
  src/app/services/database/database.service.spec.ts
  src/app/services/database/table/table.ts
  src/app/services/language/language.service.spec.ts
  src/app/services/language/language.service.ts
  src/app/services/preference-manager/preference-manager.service.spec.ts
  src/app/services/preference-manager/preference-manager.service.ts
  src/app/services/preference-manager/preferences/capacitor-storage-preferences-impl/capacitor-storage-preferences-impl.spec.ts
  src/app/services/preference-manager/preferences/capacitor-storage-preferences-impl/capacitor-storage-preferences-impl.ts
  src/app/services/preference-manager/preferences/memory-preferences-impl/memory-preferences-impl.spec.ts
  src/app/services/preference-manager/preferences/memory-preferences-impl/memory-preferences-impl.ts
  src/app/services/preference-manager/preferences/preferences.ts
  src/app/services/publisher/numbers-storage/numbers-storage-api.service.ts
  src/app/services/publisher/numbers-storage/numbers-storage-publisher.ts
  src/app/shared/shared-testing.module.ts
  src/app/shared/shared.module.ts
  src/app/utils/preferences/preference-manager.ts
  src/app/utils/preferences/preferences.ts
  tslint.json
Labels: code
