Repository numbersprotocol/capture-lite, pull requests merged in 2020-12, with the labels that each got.

#307 Implement Contact List
  src/app/pages/home/asset/contact-selection-dialog/contact-selection-dialog.component.html
  src/app/pages/home/asset/contact-selection-dialog/contact-selection-dialog.component.scss
  src/app/pages/home/asset/contact-selection-dialog/contact-selection-dialog.component.ts
  src/app/pages/home/home.page.ts
  src/app/services/database/table/capacitor-filesystem-table/capacitor-filesystem-table.spec.ts
  src/app/services/database/table/capacitor-filesystem-table/capacitor-filesystem-table.ts
  src/app/services/database/table/table.ts
  src/app/services/dia-backend/auth/dia-backend-auth.service.spec.ts
  src/app/services/dia-backend/contact/dia-backend-contact-repository.service.spec.ts
  src/app/services/dia-backend/contact/dia-backend-contact-repository.service.ts
  src/app/utils/rx-operators.ts
Labels: enhancement

#321 Implement the not-uploaded overlay and re-upload click event for Captures
  src/app/pages/home/home.page.html
  src/app/pages/home/home.page.scss
  src/app/pages/home/home.page.ts
Labels: enhancement, workaround

#320 beta7.2 fix-2
  src/app/pages/home/asset/asset.page.html
  src/app/pages/home/asset/sending-post-capture/sending-post-capture.page.html
  src/app/shared/post-capture-card/post-capture-card.component.html
  src/app/shared/post-capture-card/post-capture-card.component.scss
  src/assets/i18n/en-us.json
  src/assets/i18n/zh-tw.json
  src/global.scss
Labels: uiux

#310 Feature receive postcapture notification
  src/app/app.component.ts
  src/app/pages/home/activity/activity.module.ts
  src/app/pages/home/activity/activity.page.html
  src/app/pages/home/activity/activity.page.ts
  src/app/pages/home/activity/transaction-details/transaction-details.page.ts
  src/app/pages/home/asset/asset.page.ts
  src/app/pages/home/asset/contact-selection-dialog/contact-selection-dialog.component.ts
  src/app/pages/home/asset/information/information.page.ts
  src/app/pages/home/asset/sending-post-capture/sending-post-capture.page.ts
  src/app/pages/home/home-routing.module.ts
  src/app/pages/home/home.page.html
  src/app/pages/home/home.page.spec.ts
  src/app/pages/home/home.page.ts
  src/app/pages/home/inbox/inbox.page.html
  src/app/pages/home/inbox/inbox.page.scss
  src/app/pages/home/inbox/inbox.page.ts
  src/app/pages/home/transaction/transaction-details/transaction-details-routing.module.ts
  src/app/pages/home/transaction/transaction-details/transaction-details.module.ts
  src/app/pages/home/transaction/transaction-details/transaction-details.page.html
  src/app/pages/home/transaction/transaction-details/transaction-details.page.scss
  src/app/pages/home/transaction/transaction-details/transaction-details.page.spec.ts
  src/app/pages/home/transaction/transaction-details/transaction-details.page.ts
  src/app/pages/home/transaction/transaction-routing.module.ts
  src/app/pages/home/transaction/transaction.module.ts
  src/app/pages/home/transaction/transaction.page.html
  src/app/pages/home/transaction/transaction.page.scss
  src/app/pages/home/transaction/transaction.page.spec.ts
  src/app/pages/home/transaction/transaction.page.ts
  src/app/services/dia-backend/asset/dia-backend-asset-repository.service.ts
  src/app/services/dia-backend/auth/dia-backend-auth.service.ts
  src/app/services/dia-backend/contact/dia-backend-contact-repository.service.ts
  src/app/services/dia-backend/notification/dia-backend-notification.service.spec.ts
  src/app/services/dia-backend/notification/dia-backend-notification.service.ts
  src/app/services/dia-backend/transaction/dia-backend-transaction-repository.service.ts
  src/app/services/dia-backend/transaction/ignored-transaction-repository.service.ts
  src/app/services/push-notification/push-notification.service.spec.ts
  src/app/services/push-notification/push-notification.service.ts
  src/app/services/repositories/proof/old-proof-adapter.spec.ts
  src/app/services/repositories/proof/old-proof-adapter.ts
  src/app/services/repositories/proof/proof-repository.service.ts
  src/app/shared/capacitor-plugins/capacitor-plugins-testing.module.ts
  src/app/shared/capacitor-plugins/capacitor-plugins.module.ts
  src/app/shared/capacitor-plugins/mock-push-notifications-plugin.ts
  src/app/utils/camera.ts
  src/app/utils/rx-operators.ts
  src/app/utils/rx-operators/rx-operators.spec.ts
  src/app/utils/rx-operators/rx-operators.ts
  src/assets/i18n/en-us.json
  src/assets/i18n/zh-tw.json
Labels: enhancement

#340 Fix dia backend auth migrate
  src/app/services/dia-backend/auth/dia-backend-auth.service.ts
Labels: bug

#348 Fix webkit browser view-all button out of place
  src/app/pages/home/asset/asset.page.html
Labels: platform:ios

#358 Sort descending for captures.
  src/app/pages/home/home.page.html
  src/app/pages/home/home.page.ts
Labels: bug

#359 Collect complete device info.
  src/app/services/collector/facts/capacitor-facts-provider/capacitor-facts-provider.service.ts
Labels: bug

#370 Show Migrating Snackbar
  src/app/services/dia-backend/asset/dia-backend-asset-repository.service.ts
  src/assets/i18n/en-us.json
  src/assets/i18n/zh-tw.json
Labels: uiux

#361 Wait until All Thumbnails Loaded
  src/app/pages/home/home.page.html
  src/app/pages/home/home.page.ts
Labels: uiux

#346 Feature share watermarked postcapture
  android/app/src/main/res/xml/file_paths.xml
  package-lock.json
  package.json
  src/app/pages/home/home.page.html
  src/app/pages/home/home.page.scss
  src/app/services/dia-backend/asset/dia-backend-asset-repository.service.ts
  src/app/services/image-store/image-store.service.ts
  src/app/shared/post-capture-card/post-capture-card.component.html
  src/app/shared/post-capture-card/post-capture-card.component.ts
  src/app/utils/mime-type.ts
  src/assets/image/new-year-frame.png
  src/theme/variables.scss
Labels: enhancement

#376 Implement tutorial slides
  .vscode/settings.json
  src/app/app-routing.module.ts
  src/app/pages/home/home.page.spec.ts
  src/app/pages/home/home.page.ts
  src/app/pages/tutorial/tutorial-routing.module.ts
  src/app/pages/tutorial/tutorial.module.ts
  src/app/pages/tutorial/tutorial.page.html
  src/app/pages/tutorial/tutorial.page.scss
  src/app/pages/tutorial/tutorial.page.spec.ts
  src/app/pages/tutorial/tutorial.page.ts
  src/app/services/onboarding/onboarding.service.spec.ts
  src/app/services/onboarding/onboarding.service.ts
  src/assets/i18n/en-us.json
  src/assets/i18n/zh-tw.json
  src/assets/image/tutorial-background.png
  src/assets/image/tutorial-corona.png
Labels: enhancement

#426 Hide share button on PostCapture preview
  src/app/pages/home/asset/sending-post-capture/sending-post-capture.page.html
  src/app/shared/post-capture-card/post-capture-card.component.html
  src/app/shared/post-capture-card/post-capture-card.component.ts
Labels: uiux
